### PR TITLE
Fix badge positioning in result table for multi-digit values (#366)

### LINKED ISSUE #366: Fix UI result table badge positioning
Gap between value and badge is too large. need to fix position

### PR DESCRIPTION
**Pull request by heisdinesh**
### Problem
In the result table, the badge indicating the number of additional values was aligned correctly for single-digit numbers, but as the count increased to double or triple digits, the badge drifted further away from its associated value.

### Solution
Adjusted the styling logic to ensure consistent spacing and alignment between the value and badge, regardless of the number of digits.

### Related Issue
Closes #366

image

## Summary by Sourcery

Fix badge positioning and styling in the result table to ensure consistent alignment across different digit counts

Bug Fixes:
- Corrected badge positioning for multi-digit values in the result table, preventing misalignment as the count of additional values increases

Enhancements:
- Updated badge styling to maintain consistent spacing and visual positioning regardless of the number of digits

### CODE REVIEW

**Comment by rjchallis** [comment]
Thanks for the PR! Starting to bring the badge position under control, but there are still some issues with the positioning to solve before I can merge this. 

Looking at your screenshot, the badge is still creeping right as the length increases. Less than before, but still not a fixed width gap. Also the y position has changed so the badge now appears in line with the value and not as a superscript.

Another issue I noticed while trying this out is that longer numbers overlap the column edges when there is another column to the right, e.g. for [this table](https://goat.genomehubs.org/search?query=tax_name%28eukaryota%2A%29%20AND%20assembly_level&result=taxon&includeEstimates=true&taxonomy=ncbi&size=10&report=tree&showPhylopics=true&phylopicSize=140&treeStyle=ring&treeThreshold=2000&pointSize=15&phylopicRank=family&offset=0&fields=biosample%2Cbioproject&sortBy=scientific_name&sortOrder=asc), so I think a solution will need to reserve some space in the cell for the badge width. Sorry this was missing from the original example.

image

**Comment by heisdinesh** [comment]
Hi @rjchallis 
Adjusted badge positioning to ensure it stays visually consistent regardless of digit length.
Do review it when you get a chance. 


image

File: src/genomehubs-ui/src/client/views/components/ResultTable.jsx [hunk 1]
```diff
@@ -586,12 +586,13 @@ const formatCellValue = ({
   ) {
     let badgeContent = `+${field.length - entries.length}`;
     value = (
-      <span style={{ whiteSpace: "nowrap", marginRight: "0.75em" }}>
-        {value}
-        <StyledBadge badgeContent={badgeContent} color={"default"} max={100000}>
-          <span style={{ color: "rgba(0,0,0,0" }}>{badgeContent}</span>
+      <div style={{ paddingRight: "80px", display: "inline-block" }}>
```
Comment (rjchallis) [inline src/genomehubs-ui/src/client/views/components/ResultTable.jsx:589]: This fixed width padding adds more space than is needed for most badges. Would prefer this to be a dynamic width based on badgeContent length, e.g.
```
let badgeLength = (badgeContent.length + 1) * 8;
...
paddingRight: `${badgeLength}px`
```

**Review by rjchallis — CHANGES_REQUESTED** [review]
Thanks @heisdinesh, badge position looks much better now!

Badge colour is different now, but higher contrast in light mode isn't a bad thing so happy with the change. If you could update the padding to a dynamic width then I'll be happy to approve this

**Review by rjchallis — APPROVED** [review]
That's great, thanks. Ready to merge!
